brew_packages:
  # shell
  - direnv
  - fish
  - starship
  - zsh

  # git
  - lazygit
  - git

  # languages
  - rustup
  - basictex
  - python3

  # language servers
  - basedpyright
  - ltex-ls-plus
  - lua-language-server
  - texlab
  - tinymist

  # formatters and linters
  - prettier
  - ruff
  - stylua

  # miscellaneous CLI tools
  - fd
  - htop
  - imagemagick
  - ncdu
  - neofetch
  - ripgrep
  - zoxide
  - fzf

  # editors
  - neovim

  # terminal
  - zellij
  - ghostty

  # gui
  - spotify
  - vivaldi
  - zotero
  - skim
  - 1password
  - anytype
  - rectangle
  - slack

  # fonts
  - font-symbols-only-nerd-font
  - font-jetbrains-mono

  # - ansible  # should already be installed
